# Generated by Django 3.2.8 on 2022-06-03 01:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=500, null=True)),
                ('last_name', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.CharField(blank=True, max_length=500, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=500, null=True)),
                ('whatsapp_no', models.CharField(blank=True, max_length=500, null=True)),
                ('role', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateField(verbose_name=datetime.date(2022, 6, 3))),
            ],
        ),
    ]
