# Generated by Django 3.2.8 on 2022-06-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='number',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
