# Generated by Django 3.2.8 on 2022-06-04 05:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_register_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='created_at',
            field=models.DateField(verbose_name=datetime.date(2022, 6, 4)),
        ),
    ]
