# Generated by Django 3.2.8 on 2022-06-21 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_register_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=500, null=True)),
                ('last_name', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.CharField(blank=True, max_length=500, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=500, null=True)),
                ('whatsapp_no', models.CharField(blank=True, max_length=500, null=True)),
                ('role', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateField(verbose_name=datetime.date(2022, 6, 21))),
            ],
        ),
        migrations.AlterField(
            model_name='register',
            name='created_at',
            field=models.DateField(verbose_name=datetime.date(2022, 6, 21)),
        ),
    ]
