# Generated by Django 3.2.8 on 2022-06-21 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20220621_2200'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeletedUser',
        ),
    ]
