# Generated by Django 3.2.8 on 2022-06-26 06:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20220623_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='created_at',
            field=models.DateField(verbose_name=datetime.date(2022, 6, 26)),
        ),
    ]
