# Generated by Django 3.2.8 on 2022-06-21 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributetocustomer',
            name='date',
            field=models.DateField(verbose_name=datetime.date(2022, 6, 21)),
        ),
    ]
