# Generated by Django 3.2.8 on 2022-06-26 06:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0003_alter_distributetocustomer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributetocustomer',
            name='date',
            field=models.DateField(verbose_name=datetime.date(2022, 6, 26)),
        ),
    ]
