# Generated by Django 3.2.8 on 2022-06-26 07:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0004_alter_distributetocustomer_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(blank=True, max_length=500, null=True)),
                ('manufacturer_id', models.CharField(blank=True, max_length=500, null=True)),
                ('product_name', models.CharField(blank=True, max_length=500, null=True)),
                ('product_quantity', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.DateField(verbose_name=datetime.date(2022, 6, 26))),
            ],
        ),
    ]
