# Generated by Django 3.2.8 on 2022-06-26 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0005_totalproducts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='totalproducts',
            old_name='manufacturer_id',
            new_name='retailer_id',
        ),
    ]
