# Generated by Django 3.2.8 on 2022-06-29 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0006_rename_manufacturer_id_totalproducts_retailer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributetocustomer',
            name='date',
            field=models.DateField(verbose_name=datetime.date(2022, 6, 29)),
        ),
        migrations.AlterField(
            model_name='totalproducts',
            name='date',
            field=models.DateField(verbose_name=datetime.date(2022, 6, 29)),
        ),
    ]
