# Generated by Django 3.2.8 on 2022-06-08 02:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistributeToRetailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=1000, null=True)),
                ('username', models.CharField(blank=True, max_length=1000, null=True)),
                ('product_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('product_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('product_quantity', models.CharField(blank=True, max_length=1000, null=True)),
                ('total_price', models.CharField(blank=True, max_length=1000, null=True)),
                ('distributor_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('date', models.DateField(verbose_name=datetime.date(2022, 6, 8))),
            ],
        ),
    ]
