# Generated by Django 3.2.8 on 2022-06-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('product_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('product_price', models.CharField(blank=True, max_length=1000, null=True)),
                ('product_desc', models.CharField(blank=True, max_length=1000, null=True)),
                ('total', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
