# Generated by Django 3.2.8 on 2022-06-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0002_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='distributor',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
