# Generated by Django 3.2.8 on 2022-06-18 03:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0003_stock_distributor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distributetoretailer',
            old_name='user',
            new_name='Retailer_id',
        ),
        migrations.RenameField(
            model_name='distributetoretailer',
            old_name='username',
            new_name='Retailer_username',
        ),
        migrations.AlterField(
            model_name='distributetoretailer',
            name='date',
            field=models.DateField(verbose_name=datetime.date(2022, 6, 18)),
        ),
    ]
