# Generated by Django 3.2.8 on 2022-06-19 03:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0004_auto_20220618_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributetoretailer',
            name='date',
            field=models.DateField(verbose_name=datetime.date(2022, 6, 19)),
        ),
    ]
