# Generated by Django 3.2.8 on 2022-06-26 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0011_rename_manufacturer_id_totalproducts_retailer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='totalproducts',
            old_name='retailer_id',
            new_name='distributor_id',
        ),
    ]
