# Generated by Django 3.2.8 on 2022-06-04 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_id', models.CharField(blank=True, max_length=500, null=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('price', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=1500, null=True)),
                ('production_no', models.CharField(blank=True, max_length=150000000000000, null=True)),
                ('production_date', models.DateField(verbose_name=datetime.date(2022, 6, 4))),
            ],
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
