# Generated by Django 3.2.8 on 2022-06-05 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createdproducts',
            name='author',
        ),
    ]
