# Generated by Django 3.2.8 on 2022-06-05 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0003_createdproducts_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=500, null=True)),
                ('product_id', models.CharField(blank=True, max_length=500, null=True)),
                ('product_name', models.CharField(blank=True, max_length=500, null=True)),
                ('product_quantity', models.CharField(blank=True, max_length=500, null=True)),
                ('total_price', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.DateField(verbose_name=datetime.date(2022, 6, 5))),
            ],
        ),
    ]
