# Generated by Django 3.2.8 on 2022-06-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0004_distribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribute',
            name='take_from',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
