# Generated by Django 3.2.8 on 2022-06-06 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0006_auto_20220606_0620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distribute',
            old_name='take_from',
            new_name='manufacturer_id',
        ),
    ]
