# Generated by Django 3.2.8 on 2022-06-08 02:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0007_rename_take_from_distribute_manufacturer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribute',
            name='username',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='createdproducts',
            name='production_date',
            field=models.DateField(verbose_name=datetime.date(2022, 6, 8)),
        ),
        migrations.AlterField(
            model_name='distribute',
            name='date',
            field=models.DateField(verbose_name=datetime.date(2022, 6, 8)),
        ),
    ]
