# Generated by Django 3.2.8 on 2022-06-19 03:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0009_auto_20220618_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribute',
            name='calculation_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='createdproducts',
            name='production_date',
            field=models.DateField(verbose_name=datetime.date(2022, 6, 19)),
        ),
        migrations.AlterField(
            model_name='distribute',
            name='date',
            field=models.DateField(verbose_name=datetime.date(2022, 6, 19)),
        ),
    ]
