# Generated by Django 3.2.8 on 2022-06-26 06:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0013_auto_20220623_0755'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(blank=True, max_length=500, null=True)),
                ('manufacturer_id', models.CharField(blank=True, max_length=500, null=True)),
                ('product_name', models.CharField(blank=True, max_length=500, null=True)),
                ('product_quantity', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.DateField(verbose_name=datetime.date(2022, 6, 26))),
            ],
        ),
        migrations.AlterField(
            model_name='createdproducts',
            name='production_date',
            field=models.DateField(verbose_name=datetime.date(2022, 6, 26)),
        ),
        migrations.AlterField(
            model_name='distribute',
            name='date',
            field=models.DateField(verbose_name=datetime.date(2022, 6, 26)),
        ),
    ]
