# Generated by Django 3.2.8 on 2022-06-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_setproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setproduct',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
