# Generated by Django 3.2.8 on 2022-06-05 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_alter_setproduct_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SetProduct',
        ),
    ]
