# Generated by Django 3.2.8 on 2022-06-23 02:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0008_deleteduser_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deleteduser',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.date(2022, 6, 23)),
        ),
    ]
