# Generated by Django 3.2.8 on 2022-06-29 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0011_alter_deleteduser_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deleteduser',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.date(2022, 6, 29)),
        ),
    ]
